version: '3.8'

services:
  app:
    container_name: app
    build: ./
    environment:
      DB_PATH: $DB_PATH
    ports:
      - '8000:8000'
    restart: always

  db:
    image: postgres:latest
    container_name: database_my
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: 5432
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:latest
    container_name: test_db
    environment:
      POSTGRES_USER: mamba
      POSTGRES_PASSWORD: mamba
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
    ports:
      - "7432:5432"
    volumes:
      - pgdata_test_db:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test_db: