"""new_migration_name

Revision ID: 00e7c19ae377
Revises: 8f59ec74439f
Create Date: 2024-12-17 17:46:55.108669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e7c19ae377'
down_revision: Union[str, None] = '8f59ec74439f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lamp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('shape', sa.String(length=10), nullable=False),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('temperature', sa.String(length=10), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article')
    )
    op.drop_table('Lamps')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='manufacturers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Lamps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shape', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('base', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('fk_lamps_manufacturers', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_lamps_manufacturers'], ['manufacturers.id'], name='Lamps_fk_lamps_manufacturers_fkey'),
    sa.PrimaryKeyConstraint('id', name='Lamps_pkey')
    )
    op.drop_table('lamp')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
