"""new_migration_name

Revision ID: 8f59ec74439f
Revises: 
Create Date: 2024-12-13 17:04:35.127184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f59ec74439f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'manufacturers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('manufacturer', sa.String(length=20), nullable=False),
        sa.Column('country', sa.String(length=20), nullable=False),
        sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'Lamps',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('article', sa.UUID(), nullable=False),
        sa.Column('price', sa.INTEGER(), nullable=False),
        sa.Column('shape', sa.String(length=5), nullable=False),
        sa.Column('base', sa.String(length=5), nullable=False),
        sa.Column('temperature', sa.String(length=2), nullable=False),
        sa.Column('fk_lamps_manufacturers', sa.UUID(), nullable=False),
        sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['fk_lamps_manufacturers'], ['manufacturers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lamps')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
